FROM ubuntu:25.10

ENV container=docker
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        systemd \
        systemd-sysv \
        dbus \
        sudo \
        bash \
        ca-certificates \
        iproute2 \
        procps \
        python3 \
        python3.14 \
        python3.14-venv \
        python3-pip \
        python3-apt \
        apt-utils \
        git \
        rsync \
        build-essential \
        libsodium-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

VOLUME ["/sys/fs/cgroup"]

CMD ["/lib/systemd/systemd"]