---
- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart witness service
  ansible.builtin.systemd_service:
    name: "{{ witness_systemd_service_name }}"
    state: restarted
  when: not ansible_check_mode
